
FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8888
CMD ["voila", "Untitled1.ipynb", "--port", "$PORT", "--ip", "0.0.0.0", "--no-browser"]

